#!/usr/bin/env python3
"""
Generates hotkeys.js (the file installer.sh concatenates onto main.js — see main.js's own header
comment for why that concatenation happens at install time rather than a runtime #include) from
hotkeys.json, a structured config the web UI (shared/hotkeys-ui.html) edits.

Binding "type" maps to one main.js function each:
  windowCycle / windowToggle -> manageAppWindows(resourceClass, mode, launchArgv)
  profileCycle                -> cycleChromiumProfile(resourceClass, profileName, launchProfileName)
                                  — profileName may be ALL_PROFILES ("__all__"), meaning cycle
                                  every open window of this browser regardless of profile instead
                                  of one specific profile's own windows (main.js's
                                  cycleAnyChromiumProfile). launchProfileName is always a real,
                                  specific profile — what to launch fresh if nothing's open at
                                  all, since ALL_PROFILES alone doesn't say which one to start;
                                  defaults to profileName itself when profileName isn't
                                  ALL_PROFILES (see generate_binding_js below), so this stayed
                                  fully backward compatible for every binding saved before this
                                  parameter existed.
  tabFocus                    -> focusTab(resourceClass, profileName, urlPatterns, openUrl)
  runCommand                  -> runCommandWithToast(title, argv) — waits for argv[0] to finish
                                  (no shell) and shows a toast with its exit status and any
                                  output, rather than LaunchCommand's fire-and-forget spawn
                                  (right for the GUI apps manageAppWindows launches, wrong here:
                                  a runCommand binding's whole point is knowing whether a short
                                  CLI-style command actually worked). Generic "run this command on
                                  this key" binding, not tied to any window/tab/profile — this is
                                  what a "Reload Hotkeys" binding is made of (argv pointing at this
                                  clone's installer.sh), rather than that being a special case
                                  hardcoded into main.js/dbus_bridge.py.
  splitTab                    -> splitFocusedTab(resourceClass, profileName) — detaches the
                                  active tab of the focused window into its own new window, then
                                  places the two side by side. Port of lib/chromium.ahk's
                                  SplitFocusedTab; unlike AHK, profile isn't auto-detected from
                                  the active window's title, it's an explicit field here, same as
                                  every other browser-related binding type.
  mergeTabs                   -> mergeFocusedWindow(resourceClass, profileName) — moves every tab
                                  from the focused window into the profile's other window. Port
                                  of lib/chromium.ahk's MergeFocusedWindow, same profileName note
                                  as splitTab above.

resourceClass means two different things depending on "type", deliberately not treated the same
way. windowCycle/windowToggle target an arbitrary app (Kate, Discord, a game, ...) that genuinely
varies per binding, so it stays a field on the binding dict itself, exactly like every other field.
profileCycle/tabFocus/splitTab/mergeTabs are all inherently *about* the single browser this whole
install manages — every one of them also takes a profileName, a browser-profile concept no other
kind of app has — so their resourceClass comes from generate_hotkeys_js's/generate_binding_js's own
`browser_resource_class` parameter instead, sourced from config.py's CHROMIUM_RESOURCE_CLASS (set
once via `./installer.sh configure`) rather than hotkeys.json. This used to be a per-binding field
for these four types too, meaning the same literal string ("brave-browser") had to be retyped or
reselected into every single browser-scoped binding, with no relationship between them enforced —
switching browsers meant hand-editing every one individually, and nothing caught two bindings
quietly disagreeing about which browser they meant. Moving it up to one value fixes both.

Once hotkeys.json has been saved via the UI, it — not hand-edited hotkeys.js — is the source of
truth: every save regenerates hotkeys.js from scratch, so direct edits to hotkeys.js won't
survive the next UI save. hotkeys.js remains fully hand-editable on its own for anyone who never
touches the UI at all; nothing here runs unless something calls generate_hotkeys_js.
"""

import json

GENERATED_HEADER = (
    "// Generated by the AltTabSucks hotkeys UI (shared/hotkeys-ui.html) from hotkeys.json.\n"
    "// Hand edits here will be overwritten the next time you save in the UI — edit\n"
    "// hotkeys.json (or just use the UI) instead, unless you never use the UI at all.\n"
)

# A profileCycle binding's profileName sentinel meaning "cycle every open window of this browser,
# regardless of profile" — see the module docstring above. Must exactly match main.js's own
# ALL_PROFILES constant and shared/hotkeys-ui.html's own copy; the three aren't auto-synced (no
# shared module across Python/JS), so keep them in lockstep by hand if this ever changes.
ALL_PROFILES = "__all__"


def _js_string(value) -> str:
    """A JS string literal for value. json.dumps's escaping happens to be a valid JS string
    literal too (both escape quotes/backslashes/control chars the same way) — reused rather than
    hand-rolled to avoid getting that subtly wrong."""
    return json.dumps(str(value))


def _js_array_of_strings(values) -> str:
    return "[" + ", ".join(_js_string(v) for v in values) + "]"


# Raised for profileCycle/tabFocus/splitTab/mergeTabs when browser_resource_class is empty — these
# four no longer have a resourceClass field of their own to blame (see this module's own docstring
# for why), so the error has to point at the actual fix instead of a binding that can't have one.
_NO_BROWSER_CONFIGURED = "no browser configured — run ./installer.sh configure to set one"


def generate_binding_js(binding: dict, browser_resource_class: str = "") -> str:
    """Returns one registerShortcut(...) statement for a single binding dict. `browser_resource_class`
    is the single configured browser's resourceClass (config.py's CHROMIUM_RESOURCE_CLASS, read by
    the caller — see alttabsucks_server.py) — used for every type except windowCycle/windowToggle,
    which still take their own resourceClass from the binding dict since they target an arbitrary
    app, not necessarily the browser. Raises ValueError on a missing/invalid field — callers should
    validate before this is reached in a save flow (see alttabsucks_server.py's POST
    /hotkeys-config), but this stays strict rather than silently emitting broken JS."""
    kind = binding.get("type")
    title = (binding.get("title") or "").strip()
    key = (binding.get("key") or "").strip()
    # See this module's own docstring for why these two are treated differently.
    window_manage = kind in ("windowCycle", "windowToggle")
    resource_class = (binding.get("resourceClass") or "").strip() if window_manage \
        else (browser_resource_class or "").strip()

    if not title:
        raise ValueError(f"binding missing title: {binding!r}")
    if not key:
        raise ValueError(f"binding {title!r} missing key")

    header = (
        f"registerShortcut({_js_string(title)}, {_js_string('AltTabSucks: ' + title)},\n"
        f"    {_js_string(key)}, function () {{ "
    )

    if kind in ("windowCycle", "windowToggle"):
        if not resource_class:
            raise ValueError(f"binding {title!r} missing resourceClass")
        mode = "cycle" if kind == "windowCycle" else "toggle"
        launch_argv = binding.get("launchArgv") or []
        call = f"manageAppWindows({_js_string(resource_class)}, {_js_string(mode)}"
        if launch_argv:
            call += f", {_js_array_of_strings(launch_argv)}"
        call += ");"
    elif kind == "profileCycle":
        if not resource_class:
            raise ValueError(_NO_BROWSER_CONFIGURED)
        profile = (binding.get("profileName") or "").strip()
        if not profile:
            raise ValueError(f"binding {title!r} missing profileName")
        launch_profile = (binding.get("launchProfileName") or "").strip()
        if profile == ALL_PROFILES:
            # ALL_PROFILES alone doesn't say which profile to launch if nothing's open at all —
            # unlike the branch below, there's no sensible default to fall back to here.
            if not launch_profile:
                raise ValueError(
                    f"binding {title!r} cycles all profiles but has no launch profile set "
                    "(which one to open if nothing's running)"
                )
        elif not launch_profile:
            # Backward compatible default for every binding saved before launchProfileName
            # existed at all (or the UI simply never diverged it) — launching the same profile
            # you're cycling is the only sensible choice when there's a real, single profile.
            launch_profile = profile
        call = (
            f"cycleChromiumProfile({_js_string(resource_class)}, {_js_string(profile)}, "
            f"{_js_string(launch_profile)});"
        )
    elif kind == "tabFocus":
        if not resource_class:
            raise ValueError(_NO_BROWSER_CONFIGURED)
        profile = (binding.get("profileName") or "").strip()
        url_patterns = binding.get("urlPatterns") or []
        open_url = (binding.get("openUrl") or "").strip()
        if not profile:
            raise ValueError(f"binding {title!r} missing profileName")
        if not url_patterns:
            raise ValueError(f"binding {title!r} missing urlPatterns")
        if not open_url:
            raise ValueError(f"binding {title!r} missing openUrl")
        call = (
            f"focusTab({_js_string(resource_class)}, {_js_string(profile)}, "
            f"{_js_array_of_strings(url_patterns)}, {_js_string(open_url)});"
        )
    elif kind == "runCommand":
        argv = binding.get("argv") or []
        if not argv:
            raise ValueError(f"binding {title!r} missing argv")
        call = f'runCommandWithToast({_js_string(title)}, {_js_array_of_strings(argv)});'
    elif kind in ("splitTab", "mergeTabs"):
        if not resource_class:
            raise ValueError(_NO_BROWSER_CONFIGURED)
        profile = (binding.get("profileName") or "").strip()
        if not profile:
            raise ValueError(f"binding {title!r} missing profileName")
        fn = "splitFocusedTab" if kind == "splitTab" else "mergeFocusedWindow"
        call = f"{fn}({_js_string(resource_class)}, {_js_string(profile)});"
    else:
        raise ValueError(f"binding {title!r} has unknown type: {kind!r}")

    return header + call + " });"


def generate_hotkeys_js(config: dict, browser_resource_class: str = "") -> str:
    bindings = config.get("bindings", [])
    # A binding with "enabled": false (the hotkeys-ui badge/toggle button) produces no
    # registerShortcut call at all — it's not "registered but inert", it's simply skipped, same
    # as if it had never been in hotkeys.json. That's deliberate: it means a disabled binding
    # can't collide with anything (see the title-uniqueness check below, which only needs to
    # consider bindings that actually get emitted) and can be left half-filled-in as a draft
    # without failing validation. Missing/anything-but-exactly-false counts as enabled, matching
    # the UI's own binding.enabled === false check.
    active = [b for b in bindings if b.get("enabled") is not False]

    # registerShortcut's first argument (title) is the kglobalaccel action's unique ID within
    # this script's component — two bindings sharing a title silently collide there (confirmed
    # live: only one "discord"-named action ever existed in kglobalaccel's allShortcutInfos()
    # even with two registerShortcut("discord", ...) calls in the generated file, and the one
    # that survived kept the *first* registration's key while some later call's callback took
    # over — net effect: the second binding's key does nothing, seemingly at random depending on
    # registration order). Easy to hit via the hotkeys-ui "Dup" button, which clones a binding
    # (title included) as a starting point for editing — catching it here, at generation time,
    # turns a silently-broken-in-KWin hotkey into an immediate, readable save error instead.
    seen_titles = set()
    for binding in active:
        title = (binding.get("title") or "").strip()
        if title and title in seen_titles:
            raise ValueError(f"duplicate title {title!r} — each hotkey needs a unique title")
        seen_titles.add(title)

    parts = [GENERATED_HEADER, ""]
    for binding in active:
        parts.append(generate_binding_js(binding, browser_resource_class))
        parts.append("")
    return "\n".join(parts)
